name: release the game

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java_version: [13, 16, 18, 20]
        os: [ubuntu-latest, ubuntu-18.04, windows-2019]
        java_distributions: [zulu, liberica]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java_distributions }}
          java-version: ${{ matrix.java_version }}
          java-package: jdk+fx
          cache: 'gradle'

      - name: Run build
        shell: bash
        run: |
          ./gradlew build --stacktrace
