name: release the game

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 20
          java-package: jdk+fx
          cache: 'gradle'


      - name: Run build
        shell: bash
        run: |
          make build

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE: ${{ github.ref != 'refs/heads/main' }}
          DEFAULT_BUMP: patch
          WITH_V: true

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*"
          tag: ${{ steps.tag.outputs.new_tag }}

      - name: Doxygen
        if: github.ref == 'refs/heads/main'
        uses: mattnotmitt/doxygen-action@v1.9.4
        with:
          doxyfile-path: './documentation.config'

      - name: GIT commit and push docs
        if: github.ref == 'refs/heads/main'
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add docs
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
