name: Test the game

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java_version: [20]
        os: [ubuntu-latest, windows-latest]
        java_distributions: [corretto, zulu, adopt, temurin, liberica, semeru]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java_distributions }}
          java-version: ${{ matrix.java_version }}
          java-package: jdk+fx
          cache: 'gradle'

      - name: Run build
        shell: bash
        run: |
          ./gradlew build
