name: Test the game

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        java_version: [17]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: ${{ matrix.java_version }}
          cache: 'gradle'

      - name: Run build
        shell: bash
        run: |
          ./gradlew build
